//
// Created by Deepak Shenoy on 4/9/23.
//

#ifndef INVADER_V_01_SHIELDS_H
#define MAX_SHIELD__GRAPHICS 16
#define NUMBER___OF__SHIELDS 4
#define SHIELD_SPRITE_XCOUNT 2
#define SHIELD_SPRITE_YCOUNT 2
#define SHIELD_SPRITE__WIDTH 64
#define SHIELD_SPRITE_HEIGHT 32
#define SHIELD_BASE_FILE_NAM "./assets/shield/shield-"
#define SHIELD_X_SCREEN_DIST (MAX_SCREEN_X_DISTANCE / NUMBER___OF__SHIELDS)
#define SHIELD_OFSET_X_VALUE (MAX_SCREEN_X_DISTANCE / NUMBER___OF__SHIELDS / 2) - ((SHIELD_SPRITE_XCOUNT * SHIELD_SPRITE__WIDTH) /2)
#define SHIELD_HEIGHT_YCOORD DEFENDER__Y_POSITION - (SHIELD_SPRITE_HEIGHT * SHIELD_SPRITE_YCOUNT) - 100
#define INVADER_V_01_SHIELDS_H

#endif //INVADER_V_01_SHIELDS_H
